AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  family-meals-lambda

  SMS-based meal ordering system using Twilio and Airtable

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Parameters:
  AirtableApiKey:
    Type: String
    Description: Airtable API Key
    NoEcho: true
  AirtableBaseKey:
    Type: String
    Description: Airtable Base Key
  TwilioAccountSid:
    Type: String
    Description: Twilio Account SID
  TwilioAuthToken:
    Type: String
    Description: Twilio Auth Token
    NoEcho: true
  TwilioPhoneNumber:
    Type: String
    Description: Twilio Phone Number (E.164 format)

Resources:
  FamilyMealsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.lambdaHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          AIRTABLE_API_KEY: !Ref AirtableApiKey
          AIRTABLE_BASE_KEY: !Ref AirtableBaseKey
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
      Events:
        TwilioWebhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
        WarmupSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Keep Lambda warm to avoid cold starts
            Input: '{"warmup": true}'

Outputs:
  TwilioWebhookApi:
    Description: "API Gateway endpoint URL for Twilio webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"